modLoader = "javafml"
loaderVersion = "[3,)"
issueTrackerURL = "https://discord.link/AntsPlugins"
license = "MIT"

[[mods]]
modId = "antsangelring"
version = "${mod_version}"
displayName = "Ant's Angel Ring"
authors = "AntTheAntster"
description = '''${mod_description}'''
#logoFile = ""

[[dependencies.antsangelring]]
modId = "neoforge"
required = true
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.antsangelring]]
modId = "minecraft"
required = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"
